name: stringtoicondata
description: String to IconData
version: 0.0.1
authors: Marlon Santos <marlon-20-12@hotmail.com>
homepage: https://github.com/MarlonSantosDev/stringtoicondata.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
